### ISSUE TITLE
Setup build for iOS

### ISSUE THREAD

**Issue by sirmammingtonham** [sirmammingtonham/smartrider#15]
apple why

**Comment by sirmammingtonham** [comment]
Fixed most of the issues and added build instructions in 1f67180713ce34a47700cb407cf759fc87e5ba67.

Still some issues deploying to devices, there's some bug that prevents you from running it on devices running iOS 13.3.1 (13.4 released a few weeks ago, should fix the issue).

Closing this for now.

**Comment by sirmammingtonham** [comment]
bruh... why apple gotta be like this.

build doesn't work on other macs, reopening until we can find a fix.

**Comment by amontes261** [comment]
See commit: da773c3b8675f99228540ce5a0c9335587a02cd5
