### ISSUE TITLE
Sliding panel issues on iOS

### ISSUE THREAD

**Issue by sirmammingtonham** [sirmammingtonham/smartrider#17]
When I tested the app on the iOS simulator, the sliding panel wouldn't actually slide, it just sort of stayed in whatever position you left it and I was unable to interact with the shuttle schedules.

Not sure if this is an issue with just the simulator, hopefully someone with a Mac can check the issue out. I wasn't able to run the app on a physical device because of the version bug, so hopefully it only happens on the simulator. I haven't seen this issue reported on the sliding panel repo.

**Comment by jlioanag** [comment]
I can check this out on my mac

**Comment by amontes261** [comment]
The sliding panel moves, it's just not smooth. Don't think its a simulator issue either because the simulator runs smooth outside of the app

**Comment by sirmammingtonham** [comment]
closing.
