### ISSUE TITLE
[Frontend Issue #1] scrolling broken on homepage sliding panel

### ISSUE THREAD

**Issue by jlioanag** [sirmammingtonham/smartrider#3]
When scrolling down on the schedule page, the entire schedule panel moves. The schedule panel should be static when scrolling through the schedule options, but move when the user scrolls the upper tab of the schedule panel.

**Comment by sirmammingtonham** [comment]
Helpful link: https://pub.dev/packages/sliding_up_panel#adding-scrollable-elements-to-the-sliding-panel

You probably have to rebuild the schedule pages to use a listview builder so we can pass the scroll controller. Will also help with the "scroll to current day" feature we talked about.

**Comment by jlioanag** [comment]
Sounds good, I'll work on the issue this week.

**Comment by sirmammingtonham** [comment]
actually i have some time to work on it you should focus on getting the themes finished

**Comment by sirmammingtonham** [comment]
Fixed the issue. Now the schedules use a listview builder to dynamically create the lists, and allows for a scroll controller to handle scrolling and closing of the sliding up panel. (There's a new file that should contain all the schedule lists) Currently disables animation for switching between schedule routes, which we may or may not want to implement again in the future (should be pretty easy, just need to find a way to handle a "multiple scroll view" error).
