### ISSUE TITLE
💡 Feature Request: Schedule UI Improvements

### ISSUE THREAD

**Issue by sirmammingtonham** [sirmammingtonham/smartrider#30]
**Is your feature request related to a problem? Please describe.**
Right now, the schedule page is pretty confusing if you just want quick information on the next couple of buses or shuttles.
We need a system that can allow you to quickly check the next couple of times for a given stop.

<img src="https://user-images.githubusercontent.com/3794630/94509612-7650e780-01c9-11eb-8773-1aef43e1148c.png" alt="screenshot1" height="400px"/>

**Describe the solution you'd like**
I'm thinking that we replace the current schedule sliding panel with something similar to the cdta bus website. 
Something like this:

<img src="https://user-images.githubusercontent.com/3794630/94509782-f7a87a00-01c9-11eb-8a36-45c9b743e11b.png" alt="screenshot1" height="400px"/>

You can click to expand a stop, and each stop will list the next 5 pickup times with an estimated arrival time.
We can then move the current schedule page to floating button if someone wants to see the full schedule.

**Additional context**
Gonna involve a lot of work manipulating the bus GTFS and shuttle data. We can start by designing the UI first, and then once the GTFS is modeled (see #24) we can start filling out the page.

See https://api.flutter.dev/flutter/widgets/AnimatedContainer-class.html and https://api.flutter.dev/flutter/material/ExpansionPanelList-class.html for ideas on how to implement the animated expansion list.

**Comment by sirmammingtonham** [comment]
yee

**Comment by Vincentqchen** [comment]
## New Table View:
![image](https://user-images.githubusercontent.com/57299266/108568040-61d7cd80-72d7-11eb-9bf6-fa67f36a48ab.png)
### New Timeline View:
![image](https://user-images.githubusercontent.com/57299266/108568099-77e58e00-72d7-11eb-8e3d-ce1a27b88738.png)
