### ISSUE TITLE
Firebase not storing new user data under Cloud Firestore

### ISSUE THREAD

**Issue by amontes261** [sirmammingtonham/smartrider#37]
Not sure if this is an iOS only bug or on both iOS and Android
New users get added to the Authentication tab, but not to the Firestore tab
User data only gets stored to onboard app cache
Pretty sure it has to do with Issue #36, where registering crashes the app

**Comment by amontes261** [comment]
![Screen Shot 2020-11-03 at 6 31 36 PM](https://user-images.githubusercontent.com/29494755/98051913-db1fe300-1e02-11eb-9375-669c7dfe6521.jpg)

**Comment by sirmammingtonham** [comment]
need to rework auth and firestore integration
