### ISSUE TITLE
⚙ Optimization: Need better way of updating gtfs database

### ISSUE THREAD

**Issue by sirmammingtonham** [sirmammingtonham/smartrider#40]
So in the gtfs `calendar.txt`, there is an `end_date` column, and it looks like the oldest date in that column is when the CDTA releases an update to their gtfs feed. 

Right now, I have to manually run the `create_db.js` to download the new GTFS feed and generate the sqlite database then redeploy the firebase functions every time that happens. In addition, it looks like the `route_id`s change each update (e.g. from 87-184 to 87-185), which is a problem because some of those route ids are hardcoded in the app for querying the backend and stuff and we want to avoid app updates unless strictly necessary (can probably be solved by creating another endpoint in the API for retrieving current `route_ids` but we already have like 5 requests to the backend on app launch which is pretty slow).

Ideally, we would create some way to translate the gtfs data into our firestore nosql database so we can have the entire database hosted in the cloud, and then write a cloud function that runs once in a while to update it without having to redeploy all the functions. Unfortunately that will also require rewriting basically every backend function since we won't be able to use SQL queries. 

Low-priority, but something we need to consider. Next GTFS update is 12/31.

**Comment by BoyuChen118** [comment]
lgtm

**Comment by BoyuChen118** [comment]
We used google cloud pubsub to schedule database updates.  In addition, we added in date checking so the database is only updated if it's expired.
