### ISSUE TITLE
💡 Feature Request: Profile Page

### ISSUE THREAD

**Issue by Vincentqchen** [sirmammingtonham/smartrider#41]
**Is your feature request related to a problem? Please describe.**
Create a better looking UI for the profile page and add additional features.

**Features to be added**

- Change password

- Link to report bugs

- Link for feature requests 

- Optional profile picture/updating profile picture

**Comment by sirmammingtonham** [comment]
profile page is kil in 9f2c6f2a5c9d76a162d74d0a0bee987d8f5e1c1a

(moving the profile settings to the settings page)
