### ISSUE TITLE
💡 Feature Request: Saferide Search Bar Redesign

### ISSUE THREAD

**Issue by jlioanag** [sirmammingtonham/smartrider#48]
**Is your feature request related to a problem? Please describe.**
Saferide search pop-up does not fit our current UI.

**Describe the solution you'd like**
Create a flush search bar for saferide.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by sirmammingtonham** [comment]
implemented in 59b0b8930c58795b9f7add5aab2f1c99c6c615d1
