### ISSUE TITLE
💡 Feature Request: Feature Discovery

### ISSUE THREAD

**Issue by Vincentqchen** [sirmammingtonham/smartrider#49]
# Feature Discovery
**Issue at hand**
While the onboarding screen may give users an overview of what smartrider does and some of its major features, they still won't know how to access those features. This is where the feature discovery comes in

**Describe the solution you'd like**
Using the [feature discovery](https://pub.dev/packages/feature_discovery) package in flutter, this feature will give users a simple rundown of where different features of the app are at right after they've gone through the onboarding screen. 

**Describe alternatives you've considered**
Not many other alternatives to this. 

**Additional context**
![image](https://user-images.githubusercontent.com/57299266/108916966-04a48a80-75fd-11eb-9c46-25297c7637b1.png)

**Comment by sirmammingtonham** [comment]
Version 1 completed. Needs to be redone now, tracking in #66
