### ISSUE TITLE
🐛 Bug Report: Bottom overflow on main screen

### ISSUE THREAD

**Issue by deanvogel** [sirmammingtonham/smartrider#58]
The welcome screen and login/register screen have bottom overflows, found in the web build

![image](https://user-images.githubusercontent.com/71905387/122114059-db4c7c00-cdf0-11eb-90d6-9dd01ad7902e.png)

Can most likely be fixed with widget resizing

**Comment by sirmammingtonham** [comment]
fixed at some point lol
