### ISSUE TITLE
🐛 Bug Report: Web App errors after login screen

### ISSUE THREAD

**Issue by deanvogel** [sirmammingtonham/smartrider#61]
After logging in on the web app, the application errors and displays "unsupported operation: Platform._operatingSystem".
The error is reported as "Unhandled xmlhttprequest error in instance of mapbloc".

![image](https://user-images.githubusercontent.com/71905387/122116093-32ebe700-cdf3-11eb-99a0-e512cd2b69ce.png)

**Comment by sirmammingtonham** [comment]
fixed by changing local_notfications package to awesome_notifications
