### ISSUE TITLE
🔨 To-Do: Estimated Safe Ride Wait Time in Cloud Functions

### ISSUE THREAD

**Issue by sirmammingtonham** [sirmammingtonham/smartrider#62]
1. Need to write a cloud function that looks through orders, calculates the estimated wait time of a new order, and updates the wait times of all orders in the collection with status == 'WAITING' once a driver completes a ride.
    - This wait time estimate gets stored in the order document in firestore.
    - I think we can get away with very rough estimates for most of these since we are displaying the drivers' real-time locations on the map (and we probably need to use google directions API to get accurate estimates which is $$$).
2. We read the wait estimate and display it on the saferide status widget in the smartrider app (where it says TODO: waiting countdown).

**Comment by BoyuChen118** [comment]
Implemented wait time estimation using exponential averaging. 
f857d0063e51feda0b51f78d2ac0516b9a2c246b
d038587cd6d28ac786679e59b00b34f7bd3a704d
