### ISSUE TITLE
🔨 To-Do: Disable Safe Ride Textfield Depending on Time

### ISSUE THREAD

**Issue by sirmammingtonham** [sirmammingtonham/smartrider#63]
1. Disable the saferide textfield in the search bar widget if the hours are before 7pm or after 12am. 
2. We only want this during production (since we want to be able to test during all hours), so use the `kReleaseMode` variable by importing `import 'package:flutter/foundation.dart';` to only disable if true.
3. The best place to add this is on line 121 in `apps/smartrider/lib/widgets/search_bar.dart`. Just return a disabled `TextField` with some text like "Saferide Starts at 7pm" instead.

**Comment by deanvogel** [comment]
Done with commit a999517a0e7d8c4b18ce797b9ed6c2a818eeb02a and commit e482d383bd8e7a19b87e55b4eeac98c6b5c8f73
