### ISSUE TITLE
🔨 To-Do: Add Map Icons to Legend, Adjust Size, Fix Animation

### ISSUE THREAD

**Issue by sirmammingtonham** [sirmammingtonham/smartrider#65]
1. Add map icons to the legend (i.e. bus markers for the bus page, shuttle markers for the shuttle page, etc.)
2. Adjust the size using `sizer`, and make legend resize depending on contents.
3. Fix animation; when the legend is opened or closed, the position of the button moves briefly (see below)

![image](https://cdn.discordapp.com/attachments/740688066133622886/866787497286565958/ezgif-7-a3d2cc990006.gif)

**Comment by sirmammingtonham** [comment]
Finished in 542198ddbc453b3a6ce0c4b9348f77b3d2906e94

![image](https://cdn.discordapp.com/attachments/740688066133622886/867597148879192094/ezgif-3-b384a5297174.gif)

**Comment by deanvogel** [comment]
![image](https://user-images.githubusercontent.com/71905387/126835492-0f4fb267-f04e-40e7-942a-55436f748f9c.png)
The icon sizes do not fit correctly into the box on certain devices.
The animation is fine.
