### ISSUE TITLE
🐛 Bug Report: Bus Locations not showing up on map

### ISSUE THREAD

**Issue by jlioanag** [sirmammingtonham/smartrider#82]
**Description**
Bus indicator icons are not showing up on the map.

**To Reproduce**
1. flutter run in the dev environment
2. toggle bus routes

**Expected behavior**
Should be able to see bus indicators on map...

**Device (please complete the following information):**
 - Device: Nexus 3

**Comment by BoyuChen118** [comment]
This behavior seems to be in line with the official CDTA website, therefore, isn't an issue and can be safely closed.

**Comment by jlioanag** [comment]
https://github.com/sirmammingtonham/smartrider/commit/09e4d303ee0e642be88d6d053631f2cfe3a611a4
