### ISSUE TITLE
🐛 Bug Report: [Issue Title]

### ISSUE THREAD

**Issue by BoyuChen118** [sirmammingtonham/smartrider#83]
**Describe the bug**
Prior to the shuttle tracker overhaul there seem to be multiple shuttle routes active simultaneously. Right now it seems there's only one route active and no "route name" field in the shuttle tracker API response. Therefore we can probably hard code the route name (e.g. Main Route).

**To Reproduce**
1. Go to shuttles
2. Scroll down to see the route name ( right now it's using the ID field in shuttle tracker API response).

**Expected behavior**
Route name should be Main Route or something along the line.

**Device (please complete the following information):**
- All

**Comment by jlioanag** [comment]
Fixed
