### ISSUE TITLE
Clean Bus Polylines

### ISSUE THREAD

**Issue by sirmammingtonham** [sirmammingtonham/smartrider#9]
Right now they go over themselves which makes the dotted lines look solid sometimes, and they don't perfectly follow the roads. 

Probably involves redoing the polyline coordinates for the bus routes, being extra careful to follow the roads and not double cross.

**Comment by jlioanag** [comment]
I'm planning on getting the poly coords for the bus routes from the CDTA API, but I need to wait them to give us an API Key...

**Comment by sirmammingtonham** [comment]
added in 73b99e49e73650e2036af3d6de3ed8bd524509b2

utilizes gtfs data now
